### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined at nodeCanBeDecorated

### ISSUE THREAD

**Issue by cerebroo** [ohjames/observable-input#1]
getting this error on `ng build --prod` with Angular cli 1.5.2 and above.

**Comment by insidewhy** [comment]
I suspected that this project doesn't work with Angular 5, maybe you're the first person to use it there. I've only used it on a few Angular 4 projects.

If [this angular PR](https://github.com/angular/angular/pull/20682) gets merged I'll be able to write a less hacky version that will work in all future angulars (but it'll require using a second property, e.g. you'll have an input `values` and a stream `values$` to monitor it as a stream).

**Comment by insidewhy** [comment]
@cerebroo Ah applying two decorators two a property is broken since angular-cli 1.5.1 (see https://github.com/angular/angular-cli/issues/8434). If you read that thread it seems that they need a fix to typescript to make it work again, and that's currently available in a beta 2.7 release.

**Comment by cerebroo** [comment]
Thanks for prompt reply. I removed this lib for now and look forward to using it in future.

**Comment by insidewhy** [comment]
@cerebroo It should work now but you need angular-cli `1.6.3` and `typescript@next`

**Comment by haskelcurry** [comment]
@ohjames @cerebroo Yes it works

**Comment by front-end-developer** [comment]
its broken still in:
angular CLI: 1.7.4
Node: 7.6.0
OS: win32 ia32
Angular: 5.2.10

angular/cli: 1.7.4
angular-devkit/build-optimizer: 0.3.2
angular-devkit/core: 0.3.2
ngtools/json-schema: 1.2.0
typescript: 2.8.3
webpack: 3.11.0
