### ISSUE TITLE
Allow default value (act as BehaviorSubject?)

### ISSUE THREAD

**Issue by KoinBanks** [ohjames/observable-input#10]
Hey, I'm wondering if it would be possible to provide default value (first stream tick) via decorator.

The thing is that you can do a lot of things simply by using `combineLatest` which requires that all sources emit `at least once`. I know I can do `startWith` but it would be cool to initialize the value in the decorator itself.

What do you think?

**Comment by insidewhy** [comment]
I think it would be better to use `startWith`.
