### ISSUE TITLE
Automatically complete ReplaySubject in component's ngOnDestroy

### ISSUE THREAD

**Issue by martinsik** [ohjames/observable-input#11]
I was thinking if this package could also automatically complete all created ReplaySubject on component destruction like https://github.com/ngneat/until-destroy does. It would probably require developers to always implement `OnDestroy` interface.
Right now I have to keep track of all subscriptions myself and complete them or unsubscribe manually.

**Comment by insidewhy** [comment]
I think this isn't really one of the goals of this package, it completes all observable inputs that it creates, but anything else is outside of the aims.
