### ISSUE TITLE
Publish RxJS6-based version to NPM

### ISSUE THREAD

**Issue by haskelcurry** [ohjames/observable-input#6]
Hi guys, thanks for your great work!
I still think that this functionality has to be a native part of Angular :)
Could you please publish the RxJS6 update that you did recently to NPM?

https://www.npmjs.com/package/ng-observable-input
last publish
7 months ago

Thank you!

**Comment by insidewhy** [comment]
Published version `2.0.0`.

**Comment by insidewhy** [comment]
https://www.npmjs.com/package/observable-input <-- this is the official package.

**Comment by haskelcurry** [comment]
Great, thank you!
